### ISSUE TITLE
Great work : Issue with Invitation 

### ISSUE THREAD

**Issue by lifecrawler** [franeklubi/clubi#4]
Hi, I am learning laravel and I found this very simple and useful. You're doing great job.

Please see issue with Invitation. It is not working.

**Comment by franeklubi** [comment]
Hi! Sorry for being so late to this issue

I'm glad You're finding my work useful :D

Can You, please, explain what's supposed to be working and isn't? What invitations?

**Comment by franeklubi** [comment]
Imma mark this as closed because of no response
